DROP TABLE IF EXISTS product_info;
DROP TABLE IF EXISTS orders_date;

ALTER TABLE product ADD COLUMN price DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE orders ADD COLUMN date_created DATE DEFAULT CURRENT_DATE;
